### ISSUE TITLE
No Block Drop for Elevator TTKB 1.0.0 and 1.0.1

### ISSUE THREAD

**Issue by rxay579** [emilyploszaj/ttkb#1]
Is there meant to be a way to mine/pick up an Elevator block once you've placed it down?
The loot table for the block specifies that "ttkb:empty_elevator" is the block that should drop but I don't see any reference to the empty elevator elsewhere.  Mining the elevator block just seems to destroy it.
I've been working around the problem by changing the loot table in the jar so that the elevator drops itself when mined out.

Not sure if it's related, but I get this error in my logs.  This log snippet is from MC 1.16.1 with TTKB 1.0.1, though I wasn't getting a block drop in MC 1.15.2 with TTKB 1.0.0 either until I modified the loot table for the elevator block.

[21:58:35] [main/ERROR]: Couldn't parse loot table ttkb:blocks/elevator
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'ttkb:empty_elevator'
	at net.minecraft.class_3518.method_17995(class_3518.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518$$Lambda$5240/1009554451.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.class_3518.method_15256(class_3518.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15288(class_3518.java:135) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_77$class_78.method_413(class_77.java:55) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_77$class_78.method_443(class_77.java:40) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:83) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:448) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:169) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:165) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:456) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_60.method_20711(class_60.java:44) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_60$$Lambda$5239/1484873513.accept(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1280) [?:1.8.0_51]
	at net.minecraft.class_60.method_20712(class_60.java:42) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_60.method_18788(class_60.java:17) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4080$$Lambda$3646/39654379.accept(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4014$$Lambda$3901/79743243.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:1904) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1754) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1698) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:331) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$4014/1756309957.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$3885/1631569409.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$3352/2075210145.invoke(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1041) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.9+build.203.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.9+build.203.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.9+build.203.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:58:35] [main/ERROR]: Couldn't parse loot table ttkb:blocks/empty_elevator
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'ttkb:empty_elevator'
	at net.minecraft.class_3518.method_17995(class_3518.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518$$Lambda$5240/1009554451.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.class_3518.method_15256(class_3518.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15288(class_3518.java:135) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_77$class_78.method_413(class_77.java:55) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_77$class_78.method_443(class_77.java:40) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:83) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:448) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:169) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:165) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:456) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_60.method_20711(class_60.java:44) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_60$$Lambda$5239/1484873513.accept(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1280) [?:1.8.0_51]
	at net.minecraft.class_60.method_20712(class_60.java:42) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_60.method_18788(class_60.java:17) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4080$$Lambda$3646/39654379.accept(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4014$$Lambda$3901/79743243.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:1904) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1754) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1698) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:331) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$4014/1756309957.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$3885/1631569409.run(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312$$Lambda$3352/2075210145.invoke(Unknown Source) [intermediary-minecraft-1.16.1-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1041) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.9+build.203.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.9+build.203.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.9+build.203.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by emilyploszaj** [comment]
This is a remenant of how elevators used to work before release, thanks for pointing it out, fixed in v1.0.2
